print("Welcome to Tunnel")
print("Press enter to continue whenever you see a ...")
cont = input(str())
print("You awake lying on a cold hospital cot in an empty operating room, mind muddled, ...")
cont = input(str())
print("there is a deafening silence. Wait, why are you here, what happened? ...")
cont = input (str())
print("Never mind that for now. You look about the room and notice a fine ...")
cont = input (str())
print("layer of dust on the surrounding counters and stainless steel table. ...")
cont = input (str())
print("On the stainless steel table nearest you is a bloodied scalpel, what for? ...")
cont = input (str())
print("As your mind starts to clear you begin to regain your bearings, ...")
cont = input (str())
print("you look over your feet as you lie on the cot and see that to your North ...")
cont = input (str())
print("is a pair of heavy, beige, metal doors with small rectangular windows. Where ...")
cont = input (str())
print("the crash bar should be is instead a set of steel handles like you'd typically see ...")
cont = input (str())
print("on the exterior part of these sort of doors. ...")
cont = input (str())
print("To your East is the stainless steel table with a bloodied scalpel on top, ...")
cont = input (str())
print("beyond that is a bare wall. ...")
